name: Deploy React App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Deploy to VPS
      env:
        VPS_PASSWORD: ${{ secrets.SSH_PRIVATE_KEY }}
        VPS_USER: ${{ secrets.VPS_USER }}
        VPS_IP: ${{ secrets.VPS_IP }}
        REACT_APP_API: ${{ secrets.REACT_APP_API }}
        REACT_APP_DOMAIN: ${{ secrets.REACT_APP_DOMAIN }}
      run: |
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
        ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_IP "
          mkdir -p /var/www/unow-front
          rm -rf /var/www/unow-front/*
        "
        scp -r build/* $VPS_USER@$VPS_IP:/var/www/unow-front
